#!/usr/bin/env node
var fs = require('fs');
var triangulate = require('triangulate-image');

for(let xpath of process.argv.slice(2)) {

	fs.readFile(xpath, function ( err, buffer ) {
		const path = xpath
		if ( err ) { throw err; }

		triangulate({
		accuracy: 0.7,    		// float beteween 0 and 1
		blur: 0,         		// positive integer
		threshold: 50,    		// integer between 1 and 100
		vertexCount: 45, 		// positive integer
		fill: true,       		// boolean or string with css color (e.g '#bada55', 'red', rgba(100,100,100,0.5))
		stroke: true,     		// boolean or string with css color (e.g '#bada55', 'red', hsla(0, 50%, 52%, 0.5))
		strokeWidth: 1, 		// positive float
		gradients: true,  		// boolean
		gradientStops: 4, 		// positive integer >= 2
		lineJoin: 'miter',		// 'miter', 'round', or 'bevel'
		transparentColor: false // boolean false or string with css color
		})
			.fromBuffer( buffer )
			.toSVG()
			.then( function ( svgMarkup ) {
				fs.writeFile( path.replace(".jpg", ".svg") , svgMarkup, function ( err ) {
					if ( err ) { throw err; }
					console.log( 'created an svg file.' );
				} );
			} );
	} );

}
